[package]
name = "file_parser"
version = "0.1.0"
edition = "2021"
authors = ["Kjetil Fjellheim <kjetil@forgottendonkey.net>"]

[dependencies]
regex = "1.9.1"

[dependencies.clap]
version = "4.3.19"
features = ["derive", "cargo"]

[dependencies.queues]
version = "1.1.0"